export class RouteRequest {
  constructor(public start: number,
              public end: number,
              public maxCost: number,
              public daysToDepart: number,
              public maxTime: number,
              public startingTime: number,
              public vLength: number,
              public vHeight: number,
              public vMlc: number,
              public vWidth: number,
              public vSpacing: number,
              public vClerance: number,
              public vLoad: number,
              public vWidthRangeStart: number,
              public vWidthRangeEnd: number,
              public vWidthTop: number,
              public vFirstAxle: number,
              public vLastAxle: number,
              public vTireWidth: number,
              public vAngle: number,
              public vBolt: number,
              public vHazardous: boolean,
              public vValue: boolean,
              public vDrivers: number,
              public singleDriveTime: number,
              public dailyDriveTime: number,
              public weeklyDriveTime: number) {
  }
}
