spring.data.neo4j.uri: bolt://157.230.119.20:7687
spring.data.neo4j.username: pytong
spring.data.neo4j.password: pytong
server.port: 8081

jwt:
  secret: K0tiUGVTaFZtWXEzdDZ3OXokQyZGKUpATWNRZlRqV25acjR1N3ghQSVEKkctS2FQZFJnVWtYcDJzNXY4eS9CP0UoSCtNYlFlVGhWbVlxM3Q2dzl6JEMmRilKQE5jUmZValhuWnI0dTd4IUElRCpHLUthUGRTZ1ZrWXAzczV2OHkK
  expiration-time: 86400000

registration:
  enabled: true

traffic:
  scheduler:
    enabled: false
    cron: "0 0 0 * * *"
  client:
    read-timeout: 1000
    connect-timeout: 500
    url: "https://maps.googleapis.com"
    api-key: "AIzaSyDBXaQjU-gkEtmwgrspTXh9khAnArC97H8"